#!/usr/bin/env bash

set -e

install_homebrew () {
  echo 'installing homebrew'

  if test ! "$(which brew)"
  then
    if test "$(uname)" = "Darwin"
    then
      ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    else
      echo "skipping homebrew on Linux"
      return 1
    fi
  fi
}

ensure_ssh () {
  if test ! "$HOME/.ssh"
  then
    mkdir -p $HOME/.ssh
    chmod 0700 $HOME/.ssh
  fi

  if test ! "$HOME/.ssh/id_rsa"
  then
    echo "Before continuing, ensuring SSH keypair is copied to .ssh/"
    exit 1
  fi
}

bootstrap_others () {
  find . -name bootstrap.sh | while read bootstrapper ; do echo "running ${bootstrapper}" ; sh -c "${bootstrapper}" ; done
}

ensure_ssh
install_homebrew
bootstrap_others

sh -c ./install
